### ISSUE TITLE
ReferenceError: submitFormBuilderForm is not defined

### ISSUE THREAD

**Issue by kientv** [jembi/md-form-builder#61]
ReferenceError: submitFormBuilderForm is not defined
    at Object.<anonymous> (http://localhost/js/needs-assessment.js:405:26)
    at Object.invoke (http://localhost/resources/js/base.js:14557:21)
    at $controllerInit (http://localhost/resources/js/base.js:20032:36)
    at nodeLinkFn (http://localhost/resources/js/base.js:19007:36)
    at compositeLinkFn (http://localhost/resources/js/base.js:18389:15)
    at publicLinkFn (http://localhost/resources/js/base.js:18280:32)
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1611:22
    at Object.<anonymous> (http://localhost/resources/js/base.js:51394:11)
    at http://localhost/resources/js/base.js:11147:38
    at invokeLinkFn (http://localhost/resources/js/base.js:19624:11) <div class="ng-bounceInUp ng-fluid ng-scope" ui-view="">

**Comment by BMartinos** [comment]
Hi kientv. The submitFormBuilderForm function needs to be defined which then gets attched to the FormBuilder schema. Below is a basic example of how to write the submit function. 

`
const submitFormBuilderForm = (values) => {
  const defer = $q.defer()

  console.log(values)

  defer.resolve({ isValid: true, msg: '<a message to the user>'  })

  return defer.promise
}
`
